### ISSUE TITLE
Blade formatting? [Feature] request (Thanks!!)

### ISSUE THREAD

**Issue by jayenne** [matt-allan/laravel-code-style#6]
Although it's not part of this script I would very much like for it to include blade formatting too.
this would/should cope with inline php/css/js and directives.

even if it just indenting for starters (and possibly tag case)
- unless anyone knows of a CLI script that does Blade ?
- sorry for the wishlist requestin issues.

**Comment by matt-allan** [comment]
This project basically just configures [php-cs-fixer[(https://github.com/FriendsOfPHP/PHP-CS-Fixer) which uses [PHP's tokenizer](https://www.php.net/manual/en/intro.tokenizer.php) to process the source code. Since blade isn't actual PHP until it's compiled it won't tokenize properly.

Since this package just wraps php-cs-fixer and php-cs-fixer can't fix blade blade formatting is out of scope for this project but it would be really cool if someone released a separate blade formatting package.

I don't know of any CLI tools but certain code editors can format blade decently.

For Sublime Text you can install the [blade package](https://github.com/Medalink/laravel-blade), then highlight the code and run the 'Reindent lines' action to fix indentation. The [Visual Studio code Blade Snippets](https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade) package can format code. PHPStorm can format blade too.

If someone does want to write a CLI tool the syntax files from the editor plugins (i.e. [this one for Sublime](https://github.com/Medalink/laravel-blade/blob/master/blade.sublime-syntax) are a good starting point. The doctrine project has a simple [Lexer](https://github.com/doctrine/lexer) that might be helpful. I might work on that if I have some free time :grin:

**Comment by jayenne** [comment]
thank you. I appreciate your tips. (tbh, I didn't know sublime had reindent. sorry )

**Comment by matt-allan** [comment]
> tbh, I didn't know sublime had reindent

I didn't know either until this morning :laughing:

**Comment by HDVinnie** [comment]
https://github.com/shufo/blade-formatter
