### ISSUE TITLE
Config ?

### ISSUE THREAD

**Issue by mskenderian-wps** [matt-allan/laravel-code-style#7]
this is supposed to point to a file?
->notPath(database_path('migrations'))

**Comment by matt-allan** [comment]
I’m sorry, I don’t understand the question. That line is excluding the migrations because they violate one of the PSR rules and the fixer will try to rename them.

**Comment by mskenderian-wps** [comment]
Documentation states it must be a file.
exclude is what we need to use.

![image](https://user-images.githubusercontent.com/29801890/60387034-71473a80-9a52-11e9-8da8-250fbe4a1ac8.png)

**Comment by matt-allan** [comment]
It looks to me like both the docblock and the Symfony documentation both state that `notPath` accepts directories:

https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Finder/Finder.php#L271
https://symfony.com/doc/current/components/finder.html#path

The php-cs-fixer Finder just [adds a few default rules](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/edef5395dd496a217f8a43c373d90d6666cff7c2/src/Finder.php#L27), it's not modifying how `notPath` works.

Is this is causing an issue for you could you explain what the issue is? Are your migrations being modified by the fixer?

**Comment by mskenderian-wps** [comment]
Yes it is.
i just checked.

**Comment by mskenderian-wps** [comment]
any word?
